apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-gateway-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: platform-gateway-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.issuer.name }}
  dnsNames:
    - "*.{{ .Values.domain }}"
    - "{{ .Values.domain }}"
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h    # 90 days
  renewBefore: 720h  # renewed automatically 30 days before expiry
